apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: j25v8yekz-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:7ee9c96fa1085990b6155dbd962089a001c76819@sha256:627882e0e34898f7e4712de1d95e1e1fe8956bb5e6b2245aaa6f069ba6440d63
          name: container-image
